### ISSUE TITLE
assignment nao conculido

### ISSUE THREAD

**Issue by loscarlo** [tramontana-software/Python_Coding_Carlos#1]
5.2 Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below:

Invalid input
Maximum is 10
Minimum is 2

**Comment by loscarlo** [comment]
largest = None
smallest = None
while True:
    sval = input("Enter a number: ")
    if sval == "done":
        break
    try:
        ival=int(sval)

    except:
        print('Invalid input')

    continue

if largest is None:
    largest=ival
    #print(largest,'primeiro input largest')
elif ival> largest:
 	ival=largest

if smallest is None:
    smallest=ival
    #print(smallest,'primeiro input smallest')
elif ival<smallest:
    ival=smallest
    #print(smallest,'comparado smallest')

print("Maximum is", largest)
print("Minimum is", smallest)


#
largest = None
smallest = None
while True:
    sval = input("Enter a number: ")
    if sval == "done":
        break
    try:
        ival=int(sval)
#        print(ival)
    except:
        print('Invalid input')
    continue
if ival>largest:
    largest=ival
else:
    ival=smallest

print("Maximum is", largest)
print("Minimum is", smallest)
[assign_5.2.txt](https://github.com/tramontana-software/Python_Coding_Carlos/files/6523008/assign_5.2.txt)

**Comment by rkogeyama** [comment]
tem acao para mim?

**Comment by loscarlo** [comment]
largest = None
smallest = None
while True:
    sval = input("Enter a number: ")
    if sval == "done":
        break
    try:
        ival=int(sval)
    except:
        print('Invalid input')
     	continue

    for value in [ival]:
    	if smallest is None:
        	smallest = value
    	elif value < smallest:
        	smallest = value
    	elif largest is None:
        	largest = value
        elif value > largest:
            largest = value

print("Maximum is", largest)
print("Minimum is", smallest)


#5 

> tem acao para mim?
@rkogeyama 
to tentando jogar pra seu review via automacao.. mas nao sei se ta rolando..

**Comment by rkogeyama** [comment]
vc esta procurando por isso: [https://docs.github.com/pt/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule](url)

em resumo, vc vai proteger a branch e estabelecer uma regra onde um pull request soh eh aprovado se um x de pessoas autorizadas aprovarem.

**Comment by loscarlo** [comment]
> tem acao para mim?

msm caso do assign 3.1.. era pra testar se o Issue ia pra vc.. de ignorar
verifica se nao caiu um Pull request vc revisar..

**Comment by rkogeyama** [comment]
posso encerrar o issue
